scheb_two_factor:
    google:
        enabled: true
        issuer: "PerformanceID"  # <--- C'est ICI qu'il doit être
        template: "bundles/SchebTwoFactorBundle/Authentication/form.html.twig"
    
    persister: scheb_two_factor.persister.doctrine