services:
  # 1. Le conteneur PHP + Apache (Mode Prod)
  app:
    build: . 
    container_name: perfid_php
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:delegated
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=f3f6e8798600707753e18f9729864273
      # Utilisation du nom de service "database" (DNS interne Docker)
      - DATABASE_URL=mysql://root:root@database:3306/perfid?serverVersion=8.0.32&charset=utf8mb4
      # On définit les deux variantes pour être sûr que Doctrine MongoDB le voit
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_URI=mongodb://mongodb:27017
      # FIX CRITIQUE : Empêche l'erreur 500 sur DEFAULT_URI
      - DEFAULT_URI=http://localhost
      # FIX CRITIQUE : Mailer pour l'inscription
      - MAILER_DSN=null://default
      - MESSENGER_TRANSPORT_DSN=sync://
    depends_on:
      - database
      - mongodb

  # 2. MySQL
  database:
    image: mysql:8.0
    container_name: perfid_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=perfid
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --skip-name-resolve

  # 3. MongoDB
  mongodb:
    image: mongo:latest
    container_name: perfid_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=perfid_logs
    volumes:
      - mongodb_data:/data/db

  # 4. phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: perfid_pma
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=database
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - database

volumes:
  db_data:
  mongodb_data: