# 1. Route pour afficher le formulaire (appelle ton contrôleur)
2fa_login:
    path: /2fa
    controller: App\Controller\TwoFactorController::display2faForm
    methods: [GET, POST]

# 2. Route pour le traitement (gérée en interne par le bundle)
2fa_login_check:
    path: /2fa_check

# 3. Importation automatique des attributs #[Route] de tes contrôleurs
controllers:
    resource: ../src/Controller/
    type: attribute